#!/bin/bash

WDIR=/usr/local/backup-united
BACKUP_SCRIPTS=$WDIR/backup-scripts
BACKUPS=$WDIR/backups
MAILRECIPIENT=$WDIR/mail-recipient
MAILMESSAGE=$WDIR/mail-message

function pause(){
local message="$@"
[ -z $message ] && message="Press [Enter] to continue ..."
read -p "$message" readEnterKey
}

function show_menu(){
date
echo -e
tput setaf 5
echo "     BackupUnited                                 "
tput sgr0
echo "   |---------------------------------------------|"
echo "   | Backup Management Menu                      |"
echo "   |---------------------------------------------|"
echo "   | 1.Add    Backup Job  | 11.Backup List       |"
echo "   | 2.Remove Backup Job  | 12.Restore Backup    |"
echo "   | -------------------- | 13.Clean Backup      |"
echo "   | 3.Backup Job List    |                      |"
echo "   |---------------------------------------------|"
echo "   | 10.Backup Now                               |"
echo "   |---------------------------------------------|"
echo "   | 21.Scheduled Jobs                           |"
echo "   |---------------------------------------------|"
tput setaf 5
echo "                       Settings                   "
tput sgr0
echo "   |---------------------------------------------|"
echo "   | 30.Mail Sender Set.  |                      |"
echo "   | 31.Add Recipient     |                      |"
echo "   | 32.Remove Recipient  |                      |"
echo "   | 33.Recipient List    |                      |"
echo "   |---------------------------------------------|"
tput setaf 9
echo "                     -----------                  "
echo "                     ** BOARD **                  "
echo "                     -----------                  "
tput setaf 1
tput sgr0
echo "     $BOARDMSG                                    "
echo "   -----------------------------------------------"
tput setaf 9
echo ""
echo "    -----------"
echo "    | 99.Exit |"
echo "    -----------"
tput sgr0
echo -e
}

function add_backup(){

BACKUPTYPE=$(whiptail --title "Select Backup Type" --radiolist "Choose" 20 40 15 \
                "Daily" "" OFF \
                "Weekly" "" OFF \
                "Monthly" "" OFF \
                3>&1 1>&2 2>&3)
		
	if [ "$BACKUPTYPE" = "Daily" ]; then
		BACKUPTIME=$(whiptail --title "Select Hour" --radiolist "Choose" 20 40 15 \
			"00:20" "" OFF \
			"01:20" "" OFF \
                        "02:20" "" OFF \
                        "03:20" "" OFF \
                        "04:20" "" OFF \
                        "05:20" "" OFF \
                        "06:20" "" OFF \
                        "07:20" "" OFF \
                        3>&1 1>&2 2>&3)
	elif
		[ "$BACKUPTYPE" = "Weekly" ]; then
		BACKUPTIME=$(whiptail --title "Select Day" --radiolist "Choose" 20 40 15 \
			"Monday" "" OFF \
			"Tuesday" "" OFF \
                        "Wednesday" "" OFF \
                        "Thursday" "" OFF \
                        "Friday" "" OFF \
                        "Saturday" "" OFF \
                        "Sunday" "" OFF \
                        3>&1 1>&2 2>&3)
	elif
		[ "$BACKUPTYPE" = "Monthly" ]; then
		BACKUPTIME=$(whiptail --title "Select Day" --radiolist "Choose" 20 40 15 \
			"1st  Day" "" OFF \
			"2nd  Day" "" OFF \
			"3rd  Day" "" OFF \
			"4th  Day" "" OFF \
			"5th  Day" "" OFF \
			"6th  Day" "" OFF \
			"7th  Day" "" OFF \
			"8th  Day" "" OFF \
			"9th  Day" "" OFF \
			"10th Day" "" OFF \
			"11th Day" "" OFF \
			"12th Day" "" OFF \
			"13th Day" "" OFF \
			"14th Day" "" OFF \
			"15th Day" "" OFF \
			"16th Day" "" OFF \
			"17th Day" "" OFF \
			"18th Day" "" OFF \
			"19th Day" "" OFF \
			"20th Day" "" OFF \
			"21st Day" "" OFF \
			"22nd Day" "" OFF \
			"23rd Day" "" OFF \
			"24th Day" "" OFF \
			"25th Day" "" OFF \
			"26th Day" "" OFF \
			"27th Day" "" OFF \
			"28th Day" "" OFF \
			3>&1 1>&2 2>&3)
	fi
	
if [ "$BACKUPTYPE" = "" ] || [ "$BACKUPTIME" = "" ]; then
	whiptail --title "Backup Name" --msgbox "Backup Type and Time is not null" 10 60  3>&1 1>&2 2>&3
else
	record_backup
fi
}

function record_backup(){
JOCKER=$
BACKUPFROM=$(whiptail --title "Backup From" --radiolist "Choose:"     30 40 20 \
	"Local_Directory_Backup" "" off \
	"SMB_Share_Backup" "" off 3>&1 1>&2 2>&3)
case $BACKUPFROM in
Local_Directory_Backup)
BACKUPNAME=$(whiptail --title "Backup Name" --inputbox "Please Enter Backup Name to be Defined" 10 60  3>&1 1>&2 2>&3)
BACKUPPATH=$(whiptail --title "Path of the Area" --inputbox "Please Enter the Destination of the Backup Area (/mnt/backup1,/var/www)" 10 60  3>&1 1>&2 2>&3)
cat > "$BACKUP_SCRIPTS/$BACKUPNAME" <<EOF
#!/bin/bash
#BACKUPPATH=$BACKUPPATH
#BACKUPNAME=$BACKUPNAME

if [ -d "$BACKUPPATH" ]; then
rsync -avz "$BACKUPPATH" "$BACKUPS/$BACKUPNAME"
tar -czf /usr/local/backup-united/backups/$BACKUPNAME-"$JOCKER(date +%Y%m%d-%H%M).tar.gz" /usr/local/backup-united/backups/$BACKUPNAME
echo "$BACKUPNAME Backup Successfully Taken" > /usr/local/backup-united/mail-message
else
echo "$BACKUPNAME Backup Successfully Taken" > /usr/local/backup-united/mail-message
fi
EOF
;;
SMB_Share_Backup)
echo "SMB Share Backup Menu"
BACKUPNAME=$(whiptail --title "Backup Name" --inputbox "Please Enter Backup Name to be Defined" 10 60  3>&1 1>&2 2>&3)
BACKUPPATH=$(whiptail --title "Path of the Area" --inputbox "Please Enter the Destination of the Backup Area (//SERVER_IP/SHARE)" 10 60  3>&1 1>&2 2>&3)
BACKUPUSR=$(whiptail --title "Username" --inputbox "Please Enter Username for Access" 10 60  3>&1 1>&2 2>&3)
BACKUPPWD=$(whiptail --title "Password" --inputbox "Please Enter Password for Access" 10 60  3>&1 1>&2 2>&3)
cat > "$BACKUP_SCRIPTS/$BACKUPNAME" <<EOF
#!/bin/bash
#BACKUPPATH=$BACKUPPATH
#BACKUPNAME=$BACKUPNAME

if [ -d "/tmp/$BACKUPNAME" ]; then
rm -rf /tmp/$BACKUPNAME
fi
if [ -e "/tmp/$BACKUPNAME-mountok" ]; then
rm -rf /tmp/$BACKUPNAME-mountok
fi
if [ ! -d "/usr/local/backup-united/backups/$BACKUPNAME" ]; then
mkdir /usr/local/backup-united/backups/$BACKUPNAME
fi
mkdir /tmp/$BACKUPNAME
mount -t cifs $BACKUPPATH /tmp/$BACKUPNAME -o username=$BACKUPUSR,password=$BACKUPPWD && touch /tmp/$BACKUPNAME-mountok
if [ -e "/tmp/$BACKUPNAME-mountok" ]
then
rsync -avz /tmp/$BACKUPNAME /usr/local/backup-united/backups/$BACKUPNAME
tar -czf /usr/local/backup-united/backups/$BACKUPNAME-"$JOCKER(date +%Y%m%d-%H%M).tar.gz" /usr/local/backup-united/backups/$BACKUPNAME
echo "$BACKUPNAME Backup Successfully Taken" > /usr/local/backup-united/mail-message
umount /tmp/$BACKUPNAME
rm -rf /tmp/$BACKUPNAME-mountok
else
echo "$BACKUPNAME Backup Failed" > /usr/local/backup-united/mail-message
fi
EOF

# create service
systemctl stop backupunited-$BACKUPNAME.service && systemctl disable backupunited-$BACKUPNAME.service
if [ -f "/etc/systemd/system/multi-user.target.wants/backupunited-$BACKUPNAME.service" ]; then
rm /etc/systemd/system/multi-user.target.wants/backupunited-$BACKUPNAME.service
fi
if [ -f "/etc/systemd/system/backupunited-$BACKUPNAME.service" ]; then
rm /etc/systemd/system/backupunited-$BACKUPNAME.service
fi
cp LastControl/install/machine/etc/systemd/backupunited-$BACKUPNAME.service /etc/systemd/system/
ln -s /etc/systemd/system/backupunited-$BACKUPNAME.service /etc/systemd/system/multi-user.target.wants/ (with systemctl enable)
systemctl disable lastcontrol.service

BOARDMSG="$BACKUPNAME Backup Job Successfully Added"
;;
*)
;;
esac
pause
}

function del_backup(){
	BACKUPNAME=$(whiptail --title "Backup Name" --inputbox "Please Enter Backup Name to be Deleted" 10 60  3>&1 1>&2 2>&3)
	if [ "$BACKUPNAME" = "" ]; then
		whiptail --msgbox "BackupName is Empty" 10 60 3>&1 1>&2 2>&3
	else
		if [ -e "$BACKUP_SCRIPTS/$BACKUPNAME" ]; then
			rm -rf $BACKUP_SCRIPTS/$BACKUPNAME
		else
			whiptail --msgbox "Backup Not Found!!" 10 60 3>&1 1>&2 2>&3
		fi
	fi
	pause
}

function clean_backup(){
	ls /usr/local/backup-united/backup/ > /tmp/folderlist
	numfolder=$(cat /tmp/folderlist | wc -l)
	i=1
	while [ "$i" -le $numfolder ]; do
		folder=$(ls -l | sed -n $i{p} /tmp/folderlist)
		cd /usr/local/backup-united/backup/$folder
		pwd
		rdiff-backup --remove-older-than 15D /usr/local/backup-united/backup/$folder
		i=$(( i + 1 ))
	done
	rm -rf /tmp/folderlist
	pause
}

function mail_settings(){
	MAILADDR=$(whiptail --title "Backup Name" --inputbox "Please Enter E-Mail Address" 10 60  3>&1 1>&2 2>&3)
	SMTP=$(whiptail --title "Path of the Area" --inputbox "Please Enter SMTP Address-SMTP Port your Mailserver (smtp.gmail.com:587)" 10 60  3>&1 1>&2 2>&3)
	MAILUSER=$(whiptail --title "Username" --inputbox "Please Enter Username for E-Mail Address" 10 60  3>&1 1>&2 2>&3)
	MAILPASS=$(whiptail --title "Password" --inputbox "Please Enter Password for E-Mail Address" 10 60  3>&1 1>&2 2>&3)
	MAILDOMAIN=$(whiptail --title "Domain" --inputbox "Please Enter Domain for E-Mail Address (gmail.com,xyz.net etc)" 10 60  3>&1 1>&2 2>&3)
	cat /dev/null > /etc/ssmtp/ssmtp.conf
cat > /etc/ssmtp/ssmtp.conf <<EOF
root=$MAILADDR
mailhub=$SMTP
AuthUser=$MAILUSER
AuthPass=$MAILPASS
UseTLS=YES
UseSTARTTLS=YES
rewriteDomain=$MAILDOMAIN
hostname=$HOSTNAME
FromLineOverride=YES
EOF

echo root:$MAILADDR:$SMTP
chfn -f 'backup-united' root

cp /usr/local/backup-united/notification/99-mail-sender /usr/local/backup-united/backup-scripts/
pause
}

function backup_job_list(){
	tput setaf 8
	echo "Backup Job List"
	echo "---------------"
	tput sgr0
	ls $BACKUP_SCRIPTS
	echo -e
	
	tput setaf 8	
	echo "Backup Paths"
	echo "---------------"
	tput sgr0
	#ack "mount -t cifs" "$BACKUP_SCRIPTS" | cut -d " " -f4
	#ack "BACKUPNAME=" "$BACKUP_SCRIPTS" | cut -d "=" -f2
	ack "BACKUPPATH=" "$BACKUP_SCRIPTS" | cut -d "=" -f2
	echo -e
	pause
}

function backup_now(){
	chmod +x $BACKUP_SCRIPTS/*
	run-parts $BACKUP_SCRIPTS

	NUMRECIPIENT=$(cat "$MAILRECIPIENT" | wc -l)
	i=0
	while [ "$i" -le $NUMRECIPIENT ]; do
		RECIPIENT=$(ls -l | sed -n $i{p} "$MAILRECIPIENT")
		cat $MAILMESSAGE | mutt -s "Backup United Notification" $RECIPIENT
		i=$(( i + 1 ))
	done
	pause
}

function backup_list(){
	tput setaf 8
	echo "Backups"
	echo "---------------"
	tput sgr0
	tree $BACKUPS
	pause
}

function add_recipient(){
	read -p "E-Mail Address : " EMAILADDRESS
	echo "$EMAILADDRESS" >> $MAILRECIPIENT
	pause
}

function recipient_list(){
	tput setaf 8
	echo "Mail Recipient List"
	echo "-------------------"
	tput sgr0
	cat $MAILRECIPIENT
	echo -e
	pause
}

function read_input(){
local c
read -p "Please choose from Menu numbers " c
case $c in
1)	add_backup;;
2)	del_backup;;
3)	backup_job_list;;
10)	backup_now;;
11)	backup_list;;
31)	add_recipient;;
33)	recipient_list;;
99)	exit 0 ;;
*)	
echo "Please choose from Menu numbers"
pause
esac
}

# CTRL+C, CTRL+Z
trap '' SIGINT SIGQUIT SIGTSTP

while true
do
clear
show_menu
read_input
done
