# Set path if required
#export PATH=$GOPATH/bin:/usr/local/go/bin:$PATH

export DEBIAN_FRONTEND=noninteractive

# Aliases
alias ls='ls --color=auto'
alias ll='ls -lah --color=auto'
alias grep='grep --color=auto'
alias ec="$EDITOR $HOME/.zshrc" # edit .zshrc
alias sc="source $HOME/.zshrc"  # reload zsh configuration

# Set up the prompt - if you load Theme with zplugin as in this example, this will be overriden by the Theme. If you comment out the Theme in zplugins, this will be loaded.
autoload -Uz promptinit
promptinit
prompt adam1            # see Zsh Prompt Theme below

# Use vi keybindings even if our EDITOR is set to vi
bindkey -e

setopt histignorealldups sharehistory

# Keep 5000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=65000
SAVEHIST=65000
HISTFILE=~/.zsh_history

# Use modern completion system
autoload -Uz compinit
compinit

# zplug - manage plugins
source /usr/share/zplug/init.zsh
zplug "plugins/git", from:oh-my-zsh
#zplug "plugins/sudo", from:oh-my-zsh
zplug "plugins/command-not-found", from:oh-my-zsh
zplug "zsh-users/zsh-syntax-highlighting"
zplug "zsh-users/zsh-autosuggestions"
zplug "zsh-users/zsh-history-substring-search"
zplug "zsh-users/zsh-completions"
zplug "junegunn/fzf"
#zplug "themes/robbyrussell", from:oh-my-zsh, as:theme   # Theme

# zplug - install/load new plugins when zsh is started or reloaded
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi
# zplug load --verbose #Shows zplug plugin load messages every time terminal is started
zplug load

# Aliases
alias ls='ls $LS_OPTIONS'
alias ll='ls $LS_OPTIONS -lh'
alias l='ls $LS_OPTIONS -lAh'
alias c='clear'
alias r='reset'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ......='cd ../../../../..'
alias off='sudo poweroff'
alias homescreen='xrandr --output HDMI-1 --same-as eDP-1 --mode 1366x768 && xrandr --output eDP-1 --off'
alias homescreen2monitor='xrandr --auto && xrandr --output HDMI-1 --left-of eDP-1 --mode 1366x768'
alias workscreen='xrandr --output HDMI-1 --same-as eDP-1 --mode 1920x1080 && xrandr --output eDP-1 --off'
alias screenshot='gnome-screenshot --interactive'

#--------------------------------------------------------
# masspull function
# pull all repos under /home/erkan/beyaz/
#--------------------------------------------------------
function masspull {
for r in /home/erkan/beyaz/*
do
        echo "################### pulling $r ..."
        cd $r
        git pull
done
cd /home/erkan/beyaz
}
